# Generated by Django 2.2.2 on 2021-03-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210220_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
